#!/bin/bash
# YouTube Local Upload Proof
# Uploads generated video to YouTube as private (or unlisted with --unlisted flag)
# Updates publish.json with video ID and status
# Usage: scripts/youtube-upload-local.sh <jobId> [--unlisted] [--dry-run]
#
# Credentials location: ~/.config/youtube/.env (central credentials store)
# Token location: ~/.youtube_tokens.json (auto-generated by youtube-auth-local.sh)

set -e

JOB_ID="${1}"
BUCKET="prochat-video-dev-909439522876-eu-north-1-an"
TMP_DIR="/tmp/youtube-upload-$$"

# Load central YouTube credentials config
CONFIG_FILE="${HOME}/.config/youtube/.env"
if [ -f "$CONFIG_FILE" ]; then
    source "$CONFIG_FILE"
fi

TOKEN_FILE="${YOUTUBE_TOKEN_FILE:-${HOME}/.youtube_tokens.json}"

# Defaults
PRIVACY_STATUS="private"
DRY_RUN=false
UNLISTED=false

# Color output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

# Parse arguments
if [ -z "$JOB_ID" ]; then
    echo "Usage: $0 <jobId> [--unlisted] [--dry-run]"
    echo ""
    echo "Examples:"
    echo "  $0 prochat-os-030                    # Upload as private"
    echo "  $0 prochat-os-030 --dry-run          # Validate only"
    echo "  $0 prochat-os-030 --unlisted         # Upload as unlisted"
    echo "  $0 prochat-os-030 --unlisted --dry-run"
    exit 1
fi

# Parse optional flags
for arg in "${@:2}"; do
    case "$arg" in
        --unlisted)
            PRIVACY_STATUS="unlisted"
            UNLISTED=true
            ;;
        --dry-run)
            DRY_RUN=true
            ;;
        *)
            echo "Unknown option: $arg"
            exit 1
            ;;
    esac
done

echo "==========================================="
echo "YouTube Local Upload Proof"
echo "==========================================="
echo ""
echo "Job ID: $JOB_ID"
echo "Privacy: $PRIVACY_STATUS"
echo "Dry-run: $DRY_RUN"
echo ""

# Clean up on exit
cleanup() {
    if [ -d "$TMP_DIR" ]; then
        rm -rf "$TMP_DIR"
    fi
}
trap cleanup EXIT

# Step 1: Check OAuth token
echo "[1/8] Checking OAuth token..."

if [ ! -f "$TOKEN_FILE" ]; then
    echo -e "${RED}❌ ERROR: Token file not found: $TOKEN_FILE${NC}"
    echo ""
    echo "Run: scripts/youtube-auth-local.sh"
    exit 1
fi

ACCESS_TOKEN=$(jq -r '.access_token // empty' "$TOKEN_FILE" 2>/dev/null)
REFRESH_TOKEN=$(jq -r '.refresh_token // empty' "$TOKEN_FILE" 2>/dev/null)
CREATED_AT=$(jq -r '.created_at // empty' "$TOKEN_FILE" 2>/dev/null)
EXPIRES_IN=$(jq -r '.expires_in // empty' "$TOKEN_FILE" 2>/dev/null)

if [ -z "$ACCESS_TOKEN" ] || [ -z "$REFRESH_TOKEN" ]; then
    echo -e "${RED}❌ ERROR: Invalid token file${NC}"
    exit 1
fi

# Check token expiry and refresh if needed
CURRENT_TIME=$(date +%s)
EXPIRY_TIME=$((CREATED_AT + EXPIRES_IN))
SECONDS_REMAINING=$((EXPIRY_TIME - CURRENT_TIME))

if [ $SECONDS_REMAINING -lt 300 ]; then
    echo "⚠ Token expiring soon, refreshing..."

    # Refresh token
    if [ -z "${YOUTUBE_CLIENT_ID}" ] || [ -z "${YOUTUBE_CLIENT_SECRET}" ]; then
        # Try to read from client_secret file
        CLIENT_SECRET_FILE="${HOME}/.youtube_client_secret.json"
        if [ ! -f "$CLIENT_SECRET_FILE" ]; then
            echo -e "${RED}❌ ERROR: Cannot refresh token (missing credentials)${NC}"
            echo "Run: scripts/youtube-auth-local.sh"
            exit 1
        fi
        CLIENT_ID=$(jq -r '.installed.client_id' "$CLIENT_SECRET_FILE")
        CLIENT_SECRET=$(jq -r '.installed.client_secret' "$CLIENT_SECRET_FILE")
    else
        CLIENT_ID="${YOUTUBE_CLIENT_ID}"
        CLIENT_SECRET="${YOUTUBE_CLIENT_SECRET}"
    fi

    REFRESH_RESPONSE=$(curl -s -X POST https://oauth2.googleapis.com/token \
        -d "client_id=${CLIENT_ID}" \
        -d "client_secret=${CLIENT_SECRET}" \
        -d "refresh_token=${REFRESH_TOKEN}" \
        -d "grant_type=refresh_token")

    NEW_ACCESS_TOKEN=$(echo "$REFRESH_RESPONSE" | jq -r '.access_token // empty')
    if [ -z "$NEW_ACCESS_TOKEN" ]; then
        echo -e "${RED}❌ ERROR: Token refresh failed${NC}"
        echo "Response: $REFRESH_RESPONSE"
        exit 1
    fi

    # Update token file
    NEW_CREATED_AT=$(date +%s)
    NEW_EXPIRES_IN=$(echo "$REFRESH_RESPONSE" | jq -r '.expires_in')
    jq --arg at "$NEW_ACCESS_TOKEN" --arg ct "$NEW_CREATED_AT" --arg ei "$NEW_EXPIRES_IN" \
        '.access_token = $at | .created_at = ($ct | tonumber) | .expires_in = ($ei | tonumber)' \
        "$TOKEN_FILE" > "${TOKEN_FILE}.tmp" && mv "${TOKEN_FILE}.tmp" "$TOKEN_FILE"

    ACCESS_TOKEN="$NEW_ACCESS_TOKEN"
    echo "✓ Token refreshed"
fi

echo -e "${GREEN}✓ Token valid (${SECONDS_REMAINING}s remaining)${NC}"
echo ""

# Step 2: Read publish.json from S3
echo "[2/8] Reading publish.json from S3..."

PUBLISH_JSON=$(aws s3 cp "s3://$BUCKET/jobs/$JOB_ID/metadata/publish.json" - --region eu-north-1 2>/dev/null)

if [ -z "$PUBLISH_JSON" ]; then
    echo -e "${RED}❌ ERROR: publish.json not found${NC}"
    exit 1
fi

PUBLISH_STATUS=$(echo "$PUBLISH_JSON" | jq -r '.publishStatus // "MISSING"')
VIDEO_KEY=$(echo "$PUBLISH_JSON" | jq -r '.videoKey // "MISSING"')
THUMBNAIL_KEY=$(echo "$PUBLISH_JSON" | jq -r '.thumbnailKey // "MISSING"')
TITLE=$(echo "$PUBLISH_JSON" | jq -r '.title // ""')
DESCRIPTION=$(echo "$PUBLISH_JSON" | jq -r '.description // ""')
TAGS=$(echo "$PUBLISH_JSON" | jq -r '.tags // [] | @csv')

echo -e "${GREEN}✓ publish.json found${NC}"
echo "  publishStatus: $PUBLISH_STATUS"
echo "  videoKey: $VIDEO_KEY"
echo "  thumbnailKey: $THUMBNAIL_KEY"
echo ""

# Step 3: Validate publish.json
echo "[3/8] Validating publish.json..."

if [ "$PUBLISH_STATUS" != "pending" ] && [ "$PUBLISH_STATUS" != "published" ]; then
    echo -e "${RED}❌ ERROR: Invalid publishStatus: $PUBLISH_STATUS${NC}"
    echo "Expected: pending or published"
    exit 1
fi

if [ "$VIDEO_KEY" = "MISSING" ] || [ -z "$VIDEO_KEY" ]; then
    echo -e "${RED}❌ ERROR: videoKey missing${NC}"
    exit 1
fi

if [ "$THUMBNAIL_KEY" = "MISSING" ] || [ -z "$THUMBNAIL_KEY" ]; then
    echo -e "${RED}❌ ERROR: thumbnailKey missing${NC}"
    exit 1
fi

echo -e "${GREEN}✓ publish.json valid${NC}"
echo ""

# Step 4: Verify assets exist in S3
echo "[4/8] Verifying assets exist in S3..."

if ! aws s3api head-object --bucket "$BUCKET" --key "$VIDEO_KEY" --region eu-north-1 &>/dev/null; then
    echo -e "${RED}❌ ERROR: Video not found in S3: $VIDEO_KEY${NC}"
    exit 1
fi
echo "✓ Video exists"

if ! aws s3api head-object --bucket "$BUCKET" --key "$THUMBNAIL_KEY" --region eu-north-1 &>/dev/null; then
    echo -e "${RED}❌ ERROR: Thumbnail not found in S3: $THUMBNAIL_KEY${NC}"
    exit 1
fi
echo "✓ Thumbnail exists"

echo -e "${GREEN}✓ All assets verified${NC}"
echo ""

# Step 5: Download video and thumbnail to /tmp
echo "[5/8] Downloading assets to /tmp..."

mkdir -p "$TMP_DIR"

VIDEO_FILE="$TMP_DIR/video.mp4"
THUMBNAIL_FILE="$TMP_DIR/thumbnail.jpg"

aws s3 cp "s3://$BUCKET/$VIDEO_KEY" "$VIDEO_FILE" --region eu-north-1 > /dev/null
echo "✓ Video downloaded: $VIDEO_FILE"

aws s3 cp "s3://$BUCKET/$THUMBNAIL_KEY" "$THUMBNAIL_FILE" --region eu-north-1 > /dev/null
echo "✓ Thumbnail downloaded: $THUMBNAIL_FILE"

# Get file sizes
VIDEO_SIZE=$(du -h "$VIDEO_FILE" | cut -f1)
THUMBNAIL_SIZE=$(du -h "$THUMBNAIL_FILE" | cut -f1)

echo -e "${GREEN}✓ Assets ready ($VIDEO_SIZE video, $THUMBNAIL_SIZE thumbnail)${NC}"
echo ""

# Step 6: Prepare upload metadata
echo "[6/8] Preparing upload metadata..."

# Use safe fallback title if blank
if [ -z "$TITLE" ] || [ "$TITLE" = "null" ]; then
    TITLE="ProChat OS Internal Test Video"
fi

# Create metadata snippet
SNIPPET=$(cat <<EOF
{
  "title": "$TITLE",
  "description": "$DESCRIPTION",
  "tags": [],
  "categoryId": "22"
}
EOF
)

# Create status (privacy)
STATUS=$(cat <<EOF
{
  "privacyStatus": "$PRIVACY_STATUS"
}
EOF
)

echo "Title: $TITLE"
echo "Description: $DESCRIPTION"
echo "Privacy: $PRIVACY_STATUS"
echo -e "${GREEN}✓ Metadata prepared${NC}"
echo ""

# Step 7: Upload video to YouTube (or dry-run)
echo "[7/8] Uploading video to YouTube..."

if [ "$DRY_RUN" = true ]; then
    echo -e "${YELLOW}[DRY-RUN] Would upload video with:${NC}"
    echo "  Title: $TITLE"
    echo "  Description: $DESCRIPTION"
    echo "  Privacy: $PRIVACY_STATUS"
    echo ""
    VIDEO_ID="dQw4w9WgXcQ_TEST"  # Fake ID for dry-run
    echo -e "${GREEN}✓ [DRY-RUN] Video upload validation passed${NC}"
else
    echo "Uploading to YouTube API..."

    # Create metadata file for upload
    METADATA_FILE="$TMP_DIR/metadata.json"
    cat > "$METADATA_FILE" <<EOF
{
  "snippet": $SNIPPET,
  "status": $STATUS
}
EOF

    # Upload video
    UPLOAD_RESPONSE=$(curl -s -X POST https://www.googleapis.com/upload/youtube/v3/videos?uploadType=multipart \
        -H "Authorization: Bearer $ACCESS_TOKEN" \
        -F "metadata=<$METADATA_FILE;type=application/json" \
        -F "data=@$VIDEO_FILE;type=video/mp4")

    VIDEO_ID=$(echo "$UPLOAD_RESPONSE" | jq -r '.id // empty')

    if [ -z "$VIDEO_ID" ]; then
        ERROR=$(echo "$UPLOAD_RESPONSE" | jq -r '.error.message // "Unknown error"')
        echo -e "${RED}❌ Video upload failed: $ERROR${NC}"
        echo "Response: $UPLOAD_RESPONSE"
        exit 1
    fi

    echo -e "${GREEN}✓ Video uploaded successfully${NC}"
    echo "  Video ID: $VIDEO_ID"
    echo "  URL: https://www.youtube.com/watch?v=$VIDEO_ID"
fi

echo ""

# Step 8: Upload thumbnail (or dry-run)
echo "[8/8] Uploading thumbnail..."

if [ "$DRY_RUN" = true ]; then
    echo -e "${YELLOW}[DRY-RUN] Would upload thumbnail${NC}"
    echo -e "${GREEN}✓ [DRY-RUN] Thumbnail upload validation passed${NC}"
else
    THUMBNAIL_RESPONSE=$(curl -s -X POST \
        "https://www.googleapis.com/youtube/v3/thumbnails/set?videoId=$VIDEO_ID" \
        -H "Authorization: Bearer $ACCESS_TOKEN" \
        -F "image=@$THUMBNAIL_FILE")

    THUMBNAIL_SET=$(echo "$THUMBNAIL_RESPONSE" | jq -r '.items[0].default.url // empty')

    if [ -z "$THUMBNAIL_SET" ]; then
        ERROR=$(echo "$THUMBNAIL_RESPONSE" | jq -r '.error.message // "Unknown error"')
        echo -e "${YELLOW}⚠ Thumbnail upload failed (video already uploaded): $ERROR${NC}"

        # Update publish.json with partial status
        UPDATED_PUBLISH=$(echo "$PUBLISH_JSON" | jq \
            --arg vid "$VIDEO_ID" \
            --arg ts "$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
            '.platforms.youtube.status = "thumbnail_failed" |
             .platforms.youtube.videoId = $vid |
             .platforms.youtube.url = "https://www.youtube.com/watch?v=" + $vid |
             .publishStatus = "uploaded" |
             .updatedAt = $ts')

        aws s3 cp - "s3://$BUCKET/jobs/$JOB_ID/metadata/publish.json" --region eu-north-1 <<< "$(echo "$UPDATED_PUBLISH" | jq .)"

        echo ""
        echo -e "${YELLOW}⚠ Manual thumbnail upload required${NC}"
        echo "Run this command to set thumbnail manually:"
        echo "  curl -X POST 'https://www.googleapis.com/youtube/v3/thumbnails/set?videoId=$VIDEO_ID' \\"
        echo "    -H 'Authorization: Bearer <access_token>' \\"
        echo "    -F 'image=@/path/to/thumbnail.jpg'"
        echo ""
        echo -e "${YELLOW}Video preserved at:${NC}"
        echo "  https://www.youtube.com/watch?v=$VIDEO_ID"
        exit 1
    fi

    echo -e "${GREEN}✓ Thumbnail uploaded${NC}"
fi

echo ""

# Step 9: Update publish.json
echo "Updating publish.json..."

NOW=$(date -u +'%Y-%m-%dT%H:%M:%SZ')

UPDATED_PUBLISH=$(echo "$PUBLISH_JSON" | jq \
    --arg vid "$VIDEO_ID" \
    --arg ts "$NOW" \
    '.platforms.youtube.status = "uploaded" |
     .platforms.youtube.videoId = $vid |
     .platforms.youtube.url = "https://www.youtube.com/watch?v=" + $vid |
     .platforms.youtube.publishedAt = $ts |
     .publishStatus = "uploaded" |
     .updatedAt = $ts')

if [ "$DRY_RUN" = true ]; then
    echo -e "${YELLOW}[DRY-RUN] Would update publish.json:${NC}"
    echo "$UPDATED_PUBLISH" | jq .
else
    # Upload updated publish.json to S3
    aws s3 cp - "s3://$BUCKET/jobs/$JOB_ID/metadata/publish.json" --region eu-north-1 <<< "$(echo "$UPDATED_PUBLISH" | jq .)"
    echo -e "${GREEN}✓ publish.json updated in S3${NC}"
fi

echo ""
echo "==========================================="
echo -e "${GREEN}✅ YouTube Upload Proof Complete${NC}"
echo "==========================================="
echo ""
echo "Summary:"
echo "  Job ID: $JOB_ID"
echo "  Privacy: $PRIVACY_STATUS"
echo "  Video ID: $VIDEO_ID"
echo "  URL: https://www.youtube.com/watch?v=$VIDEO_ID"
echo "  Status: $([ "$DRY_RUN" = true ] && echo "DRY-RUN (validation only)" || echo "UPLOADED")"
echo ""

if [ "$DRY_RUN" = false ]; then
    echo "To delete video:"
    echo "  curl -X DELETE 'https://www.googleapis.com/youtube/v3/videos?id=$VIDEO_ID' \\"
    echo "    -H 'Authorization: Bearer <access_token>'"
    echo ""
    echo "To change privacy status:"
    echo "  curl -X PUT 'https://www.googleapis.com/youtube/v3/videos?part=status' \\"
    echo "    -H 'Authorization: Bearer <access_token>' \\"
    echo "    -H 'Content-Type: application/json' \\"
    echo "    -d '{\"id\": \"$VIDEO_ID\", \"status\": {\"privacyStatus\": \"private\"}}'"
    echo ""
fi

echo "Ready for: I-6.2c (Step Functions integration)"
echo ""
